TeoSprint15-10/NAVOGUE-FE

src/components/MemoBox/index.tsx, src/components/MemoBox/style.ts, src/components/Sidebar/index.tsx, src/components/Sidebar/style.ts, src/pages/MainPage/index.tsx, src/pages/MainPage/style.ts, src/styles/globalStyle.ts
- 메인페이지 레이아웃
- 헤더, 사이드바, 메인 컨텐츠 영역 분리
- 메인페이지 레이아웃
#7
=> style: 메인페이지 레이아웃

src/components/Header/style.ts
- style: 헤더 상단 고정되도록 수정
- 헤더가 상단에 고정되지 않아 상단에 고정되도록 수정했습니다.
- 
#11 
=> style: 헤더 상단 고정되도록 수정

package.json, src/api/index.ts, src/api/memo.ts, src/components/Card/index.tsx, src/components/CardList/index.tsx, src/components/CardList/style.ts, src/components/CardWrapper/index.tsx, src/constants/key.ts, src/data/memoList.json, src/hooks/queries/memoList.ts, src/pages/MainPage/index.tsx, src/types/index.ts, yarn.lock
- 메인 페이지 memo 데이터 받아오기
- 메인 페이지의 card UI는 수정될 예정입니다.
#4
close #4
=> feat: 메인 페이지 memo 데이터 받아오기

package.json, src/App.tsx, src/components/KakaoCallback/KakaoCallback.tsx, src/components/KakaoLogin/KakaoLogin.tsx, src/components/KakaoLogin/kakaoLoginData.tsx, src/components/KakaoLogin/style.ts, src/constants/route.ts, src/pages/LoginPage/index.tsx, yarn.lock
- main에 실수로 병합한 내용 다시 merge 합니다.
=> feat: 카카오 로그인 인가 코드 받아오는 기능 구현

src/components/Header/style.ts
=> style: 헤더 블러

package.json, src/App.tsx, src/api/index.ts, src/api/memo.ts, src/components/Header/index.tsx, src/context/MemoContext.tsx, src/types/index.ts, yarn.lock
- 키워드 검색 기능 구현
- axios 설치 후 키워드 검색 기능을 구현했습니다.
- yarn add axios 로 axios 설치했습니다.
목데이터로 콘솔에 찍었는데 캡쳐를 못해 코드로 대신합니다
#13 
=> feat: 키워드 검색 기능 구현

src/components/TagModal/index.tsx, src/components/TagModal/style.ts
- 태그 추가 모달 UI 구현
- 태그 추가 모달 UI를 구현했습니다.
-
#29 
=> style: 태그 추가 모달UI 구현

src/api/memo.ts, src/components/Button/index.tsx, src/components/MemoInputBox/index.tsx, src/hooks/useCreateMemo.ts, src/hooks/useInput.ts, src/util/isValidUrl.ts
- 메모 생성 custom hook
- 메모 생성 및 삭제 api
- url 판별 함수
- button onClick type 추가
#40
=> feat: 메모 생성

src/api/memo.ts, src/components/Button/index.tsx, src/components/Button/style.ts, src/components/FilterCheckbox/index.tsx, src/components/FilterCheckbox/style.ts, src/components/MemoInputBox/style.ts, src/hooks/useContentTypeFilter.ts, src/hooks/useInput.ts, src/pages/MainPage/index.tsx, vite.config.ts.timestamp-1687671894502-f700ad1de016f.mjs
- 컨텐츠 타입(URL, TEXT)에 따른 필터링
- type filter button UI 
- 메모 get api 인자로 params 받아오도록 변경
]
#43
=> feat: 컨텐츠 타입(URL, TEXT)에 따른 필터링

src/App.tsx, src/components/KakaoCallback/KakaoCallback.tsx, src/components/KakaoLogin/KakaoLogin.tsx, src/components/KakaoLogin/style.ts
- 카카오 로그인 인가코드 발급(백엔드 통신)
- 카카오 로그인 인가코드 발급
- env 설정에 오류가 있습니다. (원인분석 중) 기능 구현에 문제 없는 오류이니 안심하고 작업하셔도 됩니다!
-
=> fix: 카카오 로그인 인가코드 발급

src/api/tag.ts, src/components/Header/index.tsx, src/components/TagModal/index.tsx, src/pages/MainPage/index.tsx, src/types/index.ts
- 태그 추가 및 삭제 api 구현
- 태그 추가 및 삭제 api 구현
- 
#51 
=> feat: 태그 추가 및 삭제 api 구현

src/components/Card/CardList/index.tsx, src/components/Card/CardWrapper/index.tsx, src/pages/MainPage/index.tsx
=> fix: 무한스크롤 console.log

src/api/index.ts, src/api/memo.ts, src/components/Card/CardWrapper/index.tsx, src/components/Card/CardWrapper/style.ts
- 수정버튼 클릭시 활성화 UI로 변경되도록 구현하였음.
- 
- 레이아웃이 조금 깨집니다.
=> style: 수정버튼 클릭시 활성화 UI 변경

src/App.tsx, src/api/index.ts, src/api/memo.ts, src/components/Card/CardList/index.tsx, src/hooks/queries/memoList.ts, src/hooks/useIntersectionObeserver.ts, src/pages/MainPage/index.tsx
- 필터링 작업 시 무한스크롤이 적용되게 쿼리함수 수정했습니다.
-axios base url 수정하였습니다.
- #52
=> feat: 전체 메모 조회 쿼리함수 수정

src/api/memo.ts, src/components/Card/CardWrapper/index.tsx, src/hooks/useTogglePinMemo.ts, src/types/index.ts
- 메모 핀 고정 / 제거 기능 구현
#69 
close #69
=> feat: 메모 핀 고정 / 제거 기능 구현

src/components/Card/CardWrapper/index.tsx
- ex) modal component 레이아웃 설정
- 해당 pr에 담긴 작업내용을 작성해 주세요.
-
=> feat: 메모 수정기능, 삭제기능 추가

src/components/Card/CardWrapper/index.tsx, src/components/Card/CardWrapper/style.ts
=> style: 메모스타일 수정

src/components/Card/CardWrapper/index.tsx, src/components/Layout/index.tsx, src/components/TagModal/style.ts, src/pages/MainPage/index.tsx
- 태그 추가 모달 위치 수정 및 로그인페이지 헤더 제거
- 태그 추가 모달 위치 수정 및 로그인페이지 헤더 제거하였습니다.
- Header를 전역으로 세팅하지 않고 MainPage에서만 불러오도록 세팅했는데 Layout 폴더 삭제해도 될까요?
-
#81 issueNumber
close : #81 issueNumber
=> style: 태그 추가 모달 위치 수정 및 로그인페이지 헤더 제거

src/components/Card/CardWrapper/index.tsx, src/components/Card/CardWrapper/style.ts
- 메모 ui 수정
- 레이아웃 수정
- 태그 wrapper css 수정
- 확인 부탁드립니다
-
- #issueNumber
=> Style: 메모 수정 UI 변경

src/components/Card/CardWrapper/index.tsx, src/components/MemoInputBox/index.tsx
fix: 빈 문자열 메모 생성 issue & 메모 수정 issue
=> fix: 빈 문자열 메모 생성 issue & 메모 수정 issue
